# Generated by Django 5.0 on 2023-12-12 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bvn",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
    ]
