# Generated by Django 5.0 on 2023-12-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_customuser_bvn_remove_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bvn",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
