# Generated by Django 5.0 on 2023-12-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_bvn_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bvn",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.IntegerField(unique=True),
        ),
    ]
