# Generated by Django 5.0 on 2023-12-13 00:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_customuser_bvn_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="full_name",
        ),
    ]
