# Generated by Django 5.0 on 2023-12-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_customuser_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(default="default _name", max_length=100),
        ),
    ]
